# version: "3.8"
services:
  app:
    image: next-portfolio
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "3000:3000"
